# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrajPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obd_id', models.CharField(max_length=16)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('traj_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
