# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrajLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traj_id', models.IntegerField()),
                ('obd_id', models.CharField(max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
