# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsdata', '0002_trajline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajpoint',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
